# ===============================
# DATASOURCE - POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fisioterapia?options=-c%20timezone=America/Sao_Paulo
spring.datasource.username=postgres
spring.datasource.password=Sata2811@
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.web.servlet.handler.AbstractHandlerMethodMapping=TRACE
logging.level.org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping=TRACE
management.endpoints.web.exposure.include=mappings


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jackson.time-zone=America/Sao_Paulo
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

server.port = 8096

#SWAGGER a aplicacao
# Muda o caminho da interface (opcional)
springdoc.swagger-ui.path=/swagger-ui.html
# Ordena os endpoints por método HTTP (GET, POST, etc)
springdoc.swagger-ui.operationsSorter=alpha


